language: go
go:
  - "1.11.x"
  - "master"

env:
  - GO111MODULE=on

before_install:
  # Install coverage tool
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
